Adição de um sistema de marcação de ponto do logo

diff --git a/config/global b/config/global
--- a/config/global
+++ b/config/global
@@ -1,22 +1,26 @@
 #!/bin/bash
-# Fonte modular configuração global
+# Fonte modular configuração global\
+
 export timestamp=$(date +'%d%m%Y-%H%M%S')
+LOGFILE="/sdcard/termux/andistro/logs/global_${timestamp}.txt"
 
 # Link base para downloads
 export extralink="https://raw.githubusercontent.com/andistro/app/main"
-
 export NEWT_COLORS="window=,white border=black,white title=black,white textbox=black,white button=white,blue"
 
 # detector de gerenciadores de pacotes
 # Detecta o gerenciador de pacotes do sistema e executa comandos específicos
 for cmd in apt apk pacman dnf zypper; do
+    echo "COD_G000001" >> "$LOGFFILE"
     if command -v $cmd >"/sdcard/termux/andistro/logs/global_${timestamp}.txt" 2>&1; then
         #echo "Detectado: $cmd"
         pkg_cmd="$cmd"
     fi
 done
 
+
 detect_package_manager() {
+    echo "COD_G000002" >> "$LOGFFILE"
     if command -v apt >"/sdcard/termux/andistro/logs/global_${timestamp}.txt" 2>&1; then
         echo "apt"
     elif command -v apk >"/sdcard/termux/andistro/logs/global_${timestamp}.txt" 2>&1; then
@@ -32,6 +36,7 @@ GMT_date=$(date +"%Z":00)
 # VERIFICADOR DO GETPROP ==================================================================================
 # Verifica se o comando getprop existe antes de executar
 if command -v getprop > /dev/null 2>&1; then
+    echo "COD_G000003" >> "$LOGFFILE"
     android_version=$(getprop ro.build.version.release 2>/dev/null)         # Versão do Android
     android_architecture=$(getprop ro.product.cpu.abi 2>/dev/null)         # Arquitetura do aparelho
     device_manufacturer=$(getprop ro.product.manufacturer 2>/dev/null)     # Fabricante
@@ -56,13 +61,15 @@ wlan_ip_localhost=$(ifconfig 2>/dev/null | grep 'inet ' | grep broadcast | awk '
 # PACOTE DE IDIOMAS ==================================================================================
 # Irá carregar os pacotes de idiomas que tiver no sistema
 if [ -f "$PREFIX/var/lib/andistro/lib/share/locales/l10n_${system_icu_locale_code}.sh" ]; then
+    echo "COD_G000004" >> "$LOGFFILE"
     chmod +x "$PREFIX/var/lib/andistro/lib/share/locales/l10n_${system_icu_locale_code}.sh"
     source "$PREFIX/var/lib/andistro/lib/share/locales/l10n_${system_icu_locale_code}.sh"
 elif [ -f "/usr/local/bin/l10n_${system_icu_locale_code}.sh" ]; then
+    echo "COD_G000004-1" >> "$LOGFFILE"
     chmod +x "/usr/local/bin/locales/l10n_${system_icu_locale_code}.sh"
     source "/usr/local/bin/locales/l10n_${system_icu_locale_code}.sh"
 else
-    echo "$label_system_icu_locale_code_file_error $system_icu_locale_code"
+    echo "$label_system_icu_locale_code_file_error $system_icu_locale_code" | tee -a "$LOGFILE"
 fi
 
 # Variáveis de idioma
@@ -70,7 +77,6 @@ fi
 declare -A LANG_CODES
 LANG_CODES["pt-BR"]="Português do Brasil (pt-BR)"
 LANG_CODES["en-US"]="English (en-US)"
-
 
 # TERMINAL Progress  ==================================================================================
 # A barra de progresso aparece no terminal sem caixa de dialogo
@@ -80,6 +86,7 @@ LANG_CODES["en-US"]="English (en-US)"
 # Sistema de identificação pacotes instalados ==================================================================================
 
 check_packages_installed() {
+    echo "COD_G000005" >> "$LOGFFILE"
     local missing=()
     for pkg in "$@"; do
         if dpkg -s "$pkg" &> /dev/null; then
@@ -110,6 +117,7 @@ check_packages_installed() {
 # update_progress() ================================================================================
 # Função para exibir e registrar uma barra de progresso customizada, mostrando o avanço (%) no terminal e gravando cada etapa em arquivo de log.
 update_progress() {
+    echo "COD_G000006" >> "$LOGFFILE"
     local current_step=$1
     local total_steps=$2
     local percent=$((current_step * 100 / total_steps))
@@ -133,15 +141,11 @@ update_progress() {
 # \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 # ==================================================================================================
 # DIALOG ===========================================================================================
-export USER=$(whoami)
-    HEIGHT=0
-    WIDTH=100
-    CHOICE_HEIGHT=5
-    export PORT=1
 
 # DIALOG Progress ==================================================================================
 # Função para ter uma barra de progresso usando o dialog em diversas tarefas
 show_progress_dialog() {
+    echo "COD_G000007" >> "$LOGFFILE"
     local mode="$1"
     shift
 
@@ -150,6 +154,7 @@ show_progress_dialog() {
         steps-one-label)
             # Ex: show_progress_dialog steps-one "${label_etapa}" total_comandos \
             #     'comando1' 'comando2' 'comando3'
+            echo "COD_G000007-1" >> "$LOGFFILE"
             local label="$1"
             local total="$2"
             shift 2
@@ -179,7 +184,7 @@ show_progress_dialog() {
             # Ex: show_progress_dialog steps 2 \
             #     "${label_step1}" 'comando1' \
             #     "${label_step2}" 'comando2'
-
+            echo "COD_G000007-2" >> "$LOGFFILE"
             local steps="$1"
             #local timestamp=$(date +'%d%m%Y-%H%M%S')
             shift
@@ -209,7 +214,7 @@ show_progress_dialog() {
             # Ex: show_progress_dialog wget "${label}" -O arquivo URL
             # Ex: show_progress_dialog wget "${label_download}" \
             #     -O "$HOME/arquivo.tar.xz" "${url_do_arquivo}"
-
+            echo "COD_G000007-3" >> "$LOGFFILE"
             local label="$1"
             shift
             {
@@ -232,6 +237,7 @@ show_progress_dialog() {
         ;;
 
         wget-labeled)
+            echo "COD_G000007-4" >> "$LOGFFILE"
             local label="$1"
             local total="$2"
             shift 2
@@ -276,6 +282,7 @@ show_progress_dialog() {
         ;;
         
         extract)
+            echo "COD_G000007-5" >> "$LOGFFILE"
             local label="$1"
             local file="$2"
             local dest="$3"
@@ -338,7 +345,7 @@ show_progress_dialog() {
         check-packages)
             # Exemplo de uso:
             # show_progress_dialog check-packages "Verificando" pacote1 pacote2 ...
-
+            echo "COD_G000007-6" >> "$LOGFFILE"
             local title="$1"
             shift
             local packages=("$@")
@@ -385,7 +392,7 @@ show_progress_dialog() {
             ;;
 
         *)
-            echo "Modo desconhecido para show_progress_dialog: $mode" >&2
+            echo "Modo desconhecido para show_progress_dialog: $mode" >&2 | tee -a "$LOGFILE"
             return 1
         ;;
     esac
