[TESTE]

diff --git a/config/global b/config/global
--- a/config/global
+++ b/config/global
@@ -2,35 +2,41 @@
 # Fonte modular configuração global\
 
 export timestamp=$(date +'%d%m%Y-%H%M%S')
-GlobalLOGFILE="/sdcard/termux/andistro/logs/global_${timestamp}.txt"
 
-# Link base para downloads
 export extralink="https://raw.githubusercontent.com/andistro/app/main"
 export NEWT_COLORS="window=,white border=black,white title=black,white textbox=black,white button=white,blue"
 
 # detector de gerenciadores de pacotes
 # Detecta o gerenciador de pacotes do sistema e executa comandos específicos
 for cmd in apt apk pacman dnf zypper; do
-    if command -v $cmd >"$GlobalLOGFILE" 2>&1; then
+    if command -v $cmd >/dev/null 2>&1; then
         #echo "Detectado: $cmd"
-        echo "COD_G000001" >> "$GlobalLOGFILE"
         pkg_cmd="$cmd"
     fi
 done
 
-
 detect_package_manager() {
-    if command -v apt >"$GlobalLOGFILE" 2>&1; then
+    if command -v apt >/dev/null 2>&1; then
         echo "apt"
-    elif command -v apk >"$GlobalLOGFILE" 2>&1; then
+    elif command -v apk >/dev/null 2>&1; then
         echo "apk"
     else
         echo "unknown"
     fi
 }
 
+
+exit_erro() { # ao usar esse comando, o sistema encerra caso haja erro
+  if [ $? -ne 0 ]; then
+    echo "Erro na execução. Abortando instalação. Código ${error_code}"
+    exit 1
+  fi
+}
+
+
 #Formato GMT
 GMT_date=$(date +"%Z":00)
+
 
 # VERIFICADOR DO GETPROP ==================================================================================
 # Verifica se o comando getprop existe antes de executar
@@ -46,28 +52,29 @@ if command -v getprop > /dev/null 2>&1; then
     system_country_iso=$(getprop ro.csc.countryiso_code 2>/dev/null)       # Abreviação do País
     system_icu_locale_code=$(getprop persist.sys.locale 2>/dev/null)       # Locale
     system_timezone=$(getprop persist.sys.timezone 2>/dev/null)            # Timezone
-
-    device_dpi=$(getprop ro.sf.lcd_density 2>/dev/null)                     # DPI
 else
-    system_icu_locale_code=$(echo $LANG | sed 's/\..*//' | sed 's/_/-/') # Locale
+    system_icu_locale_code=$(echo $LANG | sed 's/\..*//' | sed 's/_/-/')
+    apt_system_icu_locale_code=$(echo "$LANG" | sed 's/\..*//' | sed 's/_/-/' | tr '[:upper:]' '[:lower:]')
     system_architecture=$(dpkg --print-architecture)
 fi
 
+wlan_ip_localhost=$(ifconfig 2>/dev/null | grep 'inet ' | grep broadcast | awk '{print $2}') # IP da rede 
 
-wlan_ip_localhost=$(ifconfig 2>/dev/null | grep 'inet ' | grep broadcast | awk '{print $2}') # IP da rede. Necessita do pacote net-tools
 
 # PACOTE DE IDIOMAS ==================================================================================
 # Irá carregar os pacotes de idiomas que tiver no sistema
-if [ -f "$PREFIX/var/lib/andistro/lib/share/locales/l10n_${system_icu_locale_code}.sh" ]; then
-    echo "COD_G000004" >> "$GlobalLOGFILE"
-    chmod +x "$PREFIX/var/lib/andistro/lib/share/locales/l10n_${system_icu_locale_code}.sh"
-    source "$PREFIX/var/lib/andistro/lib/share/locales/l10n_${system_icu_locale_code}.sh"
+if [ -f "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh" ]; then
+    #echo "Solicitando a fonte $PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh"
+    clear
+    chmod +x "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh"
+    source "$PREFIX/bin/andistro_files/l10n_${system_icu_locale_code}.sh"
 elif [ -f "/usr/local/bin/l10n_${system_icu_locale_code}.sh" ]; then
-    echo "COD_G000004-1" >> "$GlobalLOGFILE"
-    chmod +x "/usr/local/bin/locales/l10n_${system_icu_locale_code}.sh"
-    source "/usr/local/bin/locales/l10n_${system_icu_locale_code}.sh"
+    #echo "Solicitando a fonte /usr/local/bin/l10n_${system_icu_locale_code}.sh"
+    clear
+    chmod +x "/usr/local/bin/l10n_${system_icu_locale_code}.sh"
+    source "/usr/local/bin/l10n_${system_icu_locale_code}.sh"
 else
-    echo "$label_system_icu_locale_code_file_error $system_icu_locale_code" | tee -a "$GlobalLOGFILE"
+    echo "$label_system_icu_locale_code_file_error $system_icu_locale_code"
 fi
 
 # Variáveis de idioma
@@ -75,6 +82,7 @@ fi
 declare -A LANG_CODES
 LANG_CODES["pt-BR"]="Português do Brasil (pt-BR)"
 LANG_CODES["en-US"]="English (en-US)"
+
 
 # TERMINAL Progress  ==================================================================================
 # A barra de progresso aparece no terminal sem caixa de dialogo
@@ -84,7 +92,6 @@ LANG_CODES["en-US"]="English (en-US)"
 # Sistema de identificação pacotes instalados ==================================================================================
 
 check_packages_installed() {
-    echo "COD_G000005" >> "$GlobalLOGFILE"
     local missing=()
     for pkg in "$@"; do
         if dpkg -s "$pkg" &> /dev/null; then
@@ -112,10 +119,10 @@ check_packages_installed() {
 
 # //////////////////////////////////////////////////////////////////////////////////////////////////
 # ==================================================================================================
-# update_progress() ================================================================================
-# Função para exibir e registrar uma barra de progresso customizada, mostrando o avanço (%) no terminal e gravando cada etapa em arquivo de log.
+# update_progress() ===========================================================================================
+# ==================================================================================================
+# //////////////////////////////////////////////////////////////////////////////////////////////////
 update_progress() {
-    echo "COD_G000006" >> "$GlobalLOGFILE"
     local current_step=$1
     local total_steps=$2
     local percent=$((current_step * 100 / total_steps))
@@ -129,7 +136,7 @@ update_progress() {
     empty_bar=$(printf "%${empty_length}s" | tr " " " ")
 
     # AQUI ESTÁ O PULO DO GATO: força a saída para o terminal
-    printf "\r[%s%s] %3d%%" "$filled_bar" "$empty_bar" "$percent" >> "/sdcard/termux/andistro/logs/update_progress_${timestamp}.txt" 2>&1
+    printf "\r[%s%s] %3d%%" "$filled_bar" "$empty_bar" "$percent" > /dev/tty
 }
 
 # total_steps=2  # Número total de etapas que você quer monitorar
@@ -139,11 +146,23 @@ update_progress() {
 # \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 # ==================================================================================================
 # DIALOG ===========================================================================================
+# ==================================================================================================
+# //////////////////////////////////////////////////////////////////////////////////////////////////
+
+# DIALOG menu ==================================================================================
+# export USER=$(whoami)
+# HEIGHT=0
+# WIDTH=100
+# CHOICE_HEIGHT=5
+# export PORT=1
+
+# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
+# ==================================================================================================
+# DIALOG ===========================================================================================
 
 # DIALOG Progress ==================================================================================
 # Função para ter uma barra de progresso usando o dialog em diversas tarefas
 show_progress_dialog() {
-    echo "COD_G000007" >> "$GlobalLOGFILE"
     local mode="$1"
     shift
 
@@ -152,7 +171,6 @@ show_progress_dialog() {
         steps-one-label)
             # Ex: show_progress_dialog steps-one "${label_etapa}" total_comandos \
             #     'comando1' 'comando2' 'comando3'
-            echo "COD_G000007-1" >> "$GlobalLOGFILE"
             local label="$1"
             local total="$2"
             shift 2
@@ -166,7 +184,7 @@ show_progress_dialog() {
                     echo "$percent"
                     echo "$label"
                     echo "XXX"
-                    bash -c "$cmd" &>/dev/null
+                    bash -c "$cmd" >> "/sdcard/termux/andistro/logs/steps-one-label_${timestamp}.txt" 2>&1
                     count=$((count + 1))
                 done
 
@@ -182,7 +200,7 @@ show_progress_dialog() {
             # Ex: show_progress_dialog steps 2 \
             #     "${label_step1}" 'comando1' \
             #     "${label_step2}" 'comando2'
-            echo "COD_G000007-2" >> "$GlobalLOGFILE"
+
             local steps="$1"
             #local timestamp=$(date +'%d%m%Y-%H%M%S')
             shift
@@ -196,7 +214,7 @@ show_progress_dialog() {
                     echo "$percent"
                     echo "$lbl"
                     echo "XXX"
-                    bash -c "$cmd"  >> "$GlobalLOGFILE" 2>&1
+                    bash -c "$cmd"  >> "/sdcard/termux/andistro/logs/steps-multi-label_${timestamp}.txt" 2>&1
                     step=$((step + 1))
                     shift 2
                 done
@@ -212,11 +230,10 @@ show_progress_dialog() {
             # Ex: show_progress_dialog wget "${label}" -O arquivo URL
             # Ex: show_progress_dialog wget "${label_download}" \
             #     -O "$HOME/arquivo.tar.xz" "${url_do_arquivo}"
-            echo "COD_G000007-3" >> "$GlobalLOGFILE"
             local label="$1"
             shift
             {
-                wget "$@" >> "$GlobalLOGFILE" 2>&1
+                wget "$@" >> "/sdcard/termux/andistro/logs/wget_${timestamp}.txt" 2>&1
                 local pid=$!
                 local percent=0
                 while kill -0 "$pid" 2>/dev/null; do
@@ -235,7 +252,6 @@ show_progress_dialog() {
         ;;
 
         wget-labeled)
-            echo "COD_G000007-4" >> "$GlobalLOGFILE"
             local label="$1"
             local total="$2"
             shift 2
@@ -258,7 +274,7 @@ show_progress_dialog() {
 
                     echo -e "XXX\n$((count * 100 / total))\n${current_label}\nXXX"
 
-                    wget --tries=20 --progress=bar:force:noscroll "${wget_opts[@]}" "$url" >> "$GlobalLOGFILE" 2>&1
+                    wget --tries=20 --progress=bar:force:noscroll "${wget_opts[@]}" "$url" 2>&1 |
                     stdbuf -oL grep --line-buffered "%" |
                     stdbuf -oL sed -u -e "s,\.,,g" | awk -v count="$count" -v total="$total" -v label="$current_label" '
                         {
@@ -280,7 +296,6 @@ show_progress_dialog() {
         ;;
         
         extract)
-            echo "COD_G000007-5" >> "$GlobalLOGFILE"
             local label="$1"
             local file="$2"
             local dest="$3"
@@ -322,13 +337,13 @@ show_progress_dialog() {
 
             set +m
             (
-                "${cmd[@]}" >> "$GlobalLOGFILE" 2>&1
+                "${cmd[@]}" >/dev/null 2>&1
             ) & disown
             pid=$!
 
             {
                 i=0
-                while kill -0 "$pid" >> "$GlobalLOGFILE" 2>&1; do
+                while kill -0 "$pid" 2>/dev/null; do
                     echo $i
                     sleep 0.2
                     i=$((i + 2))
@@ -343,13 +358,12 @@ show_progress_dialog() {
         check-packages)
             # Exemplo de uso:
             # show_progress_dialog check-packages "Verificando" pacote1 pacote2 ...
-            echo "COD_G000007-6" >> "$GlobalLOGFILE"
             local title="$1"
             shift
             local packages=("$@")
             local total="${#packages[@]}"
             #local timestamp=$(date +'%d%m%Y-%H%M%S')
-            #local log_file="/sdcard/termux/andistro/logs/check_packages_${timestamp}.txt"
+            local log_file="/sdcard/termux/andistro/logs/check_packages_${timestamp}.txt"
             local pkg_manager=$(detect_package_manager)
             : > "$log_file"
 
@@ -361,9 +375,9 @@ show_progress_dialog() {
                     case "$pkg_manager" in
                         apt)
                             if dpkg -s "$pkg" &>/dev/null; then
-                                echo "$index [✓] $pkg está instalado." >> "$GlobalLOGFILE" 2>&1
+                                echo "$index [✓] $pkg está instalado." >> "$log_file" 2>&1
                             else
-                                echo "$index [✗] $pkg NÃO está instalado." >> "$GlobalLOGFILE" 2>&1
+                                echo "$index [✗] $pkg NÃO está instalado." >> "$log_file" 2>&1
                             fi
                             ;;
                         apk)
@@ -390,7 +404,7 @@ show_progress_dialog() {
             ;;
 
         *)
-            echo "Modo desconhecido para show_progress_dialog: $mode" >&2 | tee -a "$GlobalLOGFILE"
+            echo "Modo desconhecido para show_progress_dialog: $mode" >&2 | tee -a "$log_file"
             return 1
         ;;
     esac
